### ISSUE TITLE
GPT baseline block computation error

### ISSUE THREAD

**Issue by alxndrTL** [NVIDIA/ngpt#1] opened 2024-11-14 12:56 UTC
Hello,
thank you very much for open sourcing nGPT.

I have found an error in the block computation of the GPT (`use_nGPT=0`) baseline.
The computation being done is :

x = norm(x) + attn(norm(x))
x = norm(x) + mlp(norm(x))

instead of
x = x + attn(norm(x))
x = x + mlp(norm(x))

https://github.com/NVIDIA/ngpt/blob/86cc59470bcc4a1f9afceea34de9cb2396fc0dbb/model.py#L142C13-L142C26
https://github.com/NVIDIA/ngpt/blob/86cc59470bcc4a1f9afceea34de9cb2396fc0dbb/model.py#L166C13-L166C26

This is why, as reported in the README, bigger LRs make the GPT baseline diverge.
Here is the before/after fix : 
![Image](https://github.com/user-attachments/assets/1f79412c-c49b-4052-acfb-c89c7127df3b)

And indeed making the LR higher can make the GPT baseline much more effective :
![Image](https://github.com/user-attachments/assets/2038409f-c6b1-4d43-8f1a-f24cd08e719d)

As you can see in the code, this only affects the GPT baseline.
I know that your internal code is different from this repo. However, the reported speedups in the README (4x, 10x) are the same as in the paper, and maybe with a correct GPT baseline the (4x, 10x) speedup of this reproduction would be different?

Thank you.

**Comment by iloshchilov** [comment] 2024-11-19 02:49
Thank you very much for reporting this bug! This bug is specific to this reimplementation and is not present in our internal code. It appeared when putting everything in a single function. We updated the code to fix it. The resulting speedup would be smaller. 

However, there is another detail that we also fixed in the update. The original code had float32 dtype for parameters of matrices. However, in our internal code we used bfloat16. By setting parameters of matrices to bfloat16 in this code, the speedup of nGPT increases because that decrease in precision has a much greater (negative) effect on the baseline GPT than on nGPT. The speedup appears even greater than in the paper, suggesting that something still might be wrong and/or unfair. However, keeping parameters in float32 would also be unfair w.r.t. our goal to reproduce our experimental settings which had these parameters in bfloat16.  Very roughly, right now the speedup (4x for 1k and 10x for 4k) we observed in our internal code is somewhere in the middle of two speedups: when using float32 and when using bfloat16 parameters in this code. We would like to iterative more over the code to converge to a balanced reproduction of our experiments.

We updated README to reflect these observations. We also removed one figure not to oversell even greater speedup since it might be an exaggeration. Please report about any bugs you find. I will close this one because it is fixed by the updated code. Thank you for your contribution!

**Closed** 2024-11-19 02:49 UTC

**Comment by alxndrTL** [comment] 2024-11-19 09:12
Thank you for your detailed response!
Indeed the bfloat16 weights case is interesting. Maybe a wall time comparison between GPT-fp32 and nGPT-bf16 would also be relevant here.

**Comment by gabbard** [comment] 2024-12-04 15:40
>Very roughly, right now the speedup (4x for 1k and 10x for 4k) we observed in our internal code is somewhere in the middle of two speedups: when using float32 and when using bfloat16 parameters in this code. 

Can you share roughly what the speedup is when using float32 with this code?

**Comment by akhilkedia** [comment] 2024-12-09 12:32
> > Very roughly, right now the speedup (4x for 1k and 10x for 4k) we observed in our internal code is somewhere in the middle of two speedups: when using float32 and when using bfloat16 parameters in this code.
> 
> Can you share roughly what the speedup is when using float32 with this code?

I ran the 0.5B 1K context length for 10K update steps (the configuration `nGPT_1kctx_10k_lr30e-4` in `launcher.sh`).
This gave a final eval loss of `2.755`, slightly better than the reported figure in the readme. Note that this uses 16-bit parameters.

I also ran the same exact configuration and hparams using the Megatron-LM codebase for baseline GPT with float32 bit parameters.
This gave an eval loss of `2.82`, corresponding to a speedup of approx `20%` (nGPT at 8k steps ~ GPT at 10k steps).

Note - I did not search LR for baseline GPT (used same value as nGPT), and nGPT uses lower-precision for the params (16-bit).
